## Chapter 2 Exercises

### Problem 1
Assign the value 2 to the variable x and the value 3 to the variable y. Clear just the variable x.

In [1]:
x = 2
y = 3

In [2]:
del x

In [3]:
%whos

Variable   Type    Data/Info
----------------------------
y          int     3


### Problem 2
Write a line of code that generates the following error:  NameError: name "x" is not defined

In [4]:
print(x)

NameError: name 'x' is not defined

### Problem 3
Let x = 10 and y=3. Write a line of code that will make each of the following assignments.\
u=x+y, v = xy, w = x/y, z = sin(x), r = 8sin(x), s = 5sin(xy), p=x**y

### Problem 4
Show all the variables in the Jupyter notebook after you finish Problem 3.

### Problem 5
Assign string "123" to the variable S. Convert the string into a float type and assign the output to the variable N. Verify that S is a string and N is a float using the type function.

In [7]:
S = "123"
N = float(S)

print(f"Type of S: {type(S)}.\nType of N: {type(N)}")

Type of S: <class 'str'>.
Type of N: <class 'float'>


### Problem 6
Assign the string "HELLO" to the variable s1 and the string "hello" to the variable s2. Use the == operator to show that they are not equal. Use the == operator to show that s1 and s2 are equal if the lower method is used on s1. Use the == operator to show that s1 and s2 are equal if upper method is used on s2.

### Problem 7
Use the print function to generate the following strings:
- The word "Engineering" has 11 letters.
- The word "Book" has 4 letters.


In [10]:
print("The word \"Engineering\" has 11 latters.")
print("The word \"Book\" has 4 latters.")

The word "Engineering" has 11 latters.
The word "Book" has 4 latters.


### Problem 8
Check if "Python" is in "Python is great!".

In [12]:
if "Python" in "Python is great!":
    print("Yes, it is.")
else:
    print("No, it isn't.")

Yes, it is.


### Problem 9
Get the last word "great" from "Python is great!"

In [24]:
s = "Python is great!"
great = s[-len("great")-1:len(s)-1]
print(great)

great


### Problem 10
Assign list [1, 8, 9, 15] to a variable list_a and insert 2 at index 1 using the insert method. Append 4 to the list_a using the append method.

In [28]:
list_a = [1, 8, 9, 15]
list_a.insert(1, 2)
list_a.append(4)
print(list_a)

[1, 2, 8, 9, 15, 4]


### Problem 11
Sort the list_a in problem 10 in ascending order.

In [31]:
lst = [1, 8, 9, 15]
lst.sort()
print(lst)

[1, 8, 9, 15]


### Problem 12
Turn "Python is great!" into a list.

In [32]:
sentence = "Python is great!"
lst_sentence = list(sentence)

print(lst_sentence)

['P', 'y', 't', 'h', 'o', 'n', ' ', 'i', 's', ' ', 'g', 'r', 'e', 'a', 't', '!']


### Problem 13
Create one tuple with element "One", 1 and assign it to tuple_a.

In [33]:
tuple_a = ("One", 1)

### Problem 14
Get the second element in the tuple_a in Problem 13.

In [34]:
second_element = tuple_a[1]

print(second_element)

1


### Problem 15
Get the unique element from (2, 3, 2, 3, 1, 2, 5).

In [5]:
unique_lst = []
given_tuple = (2, 3, 2, 3, 1, 2, 5)

# for i in range(len(given_tuple)):
#     if given_tuple[i] in list(given_tuple).pop(i):
#         unique_lst.append(given_tuple[i])

uniqueEl = set(given_tuple)
uniqueEl

{1, 2, 3, 5}

### Problem 16
Assign (2, 3, 2) to set_a, and (1, 2, 3) to set_b. Obtain the following:
- union of set_a and set_b
- intersection of set_a and set_b
- difference of set_a to set_b using difference method

In [73]:
set_a = {2, 3, 2}
set_b = {1, 2, 3}

union_set = set_a.union(set_b)
intersection_set = set_a.intersection(set_b)
difference_set = set_a.difference(set_b)

### Problem 17
Create a dictionary that has the keys "A", "B", "C" with values "a", "b", "c" individually. Print all the keys in the dictionary

In [79]:
dict_a = {"A":"a", "B":"b", "C":"c"}
keys = dict_a.keys()
for key in keys:
    print(key)

A
B
C


### Problem 18
Check if key "B" is in the dictionary defined in Problem 17.

In [80]:
if "B" in dict_a:
    print("B is in dict_a.")
else:
    print("B is not in dict_a")

B is in dict_a.


###  Problem 19
Create array x and y, where x = [1, 4, 3, 2, 9, 4] and y=[2, 3, 4, 1, 2, 3]. Compute the assignments from Problem 3.

In [81]:
import numpy as np
x = np.array([1, 4, 3, 2, 9, 4])
y = np.array([2, 3, 4, 1, 2, 3])

u = x + y
v = x*y
w = x/y
z = np.sin(x)
r = 8*np.sin(x)
s = 5*np.sin(v)
p = x**y

### Problem 20
Generate an array with size 100 evenly spaced between −10 to 10 using linspace function in NumPy.

In [82]:
arr = np.linspace(-10, 10, 100)
arr

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

### Problem 21
Let array_a be an array [-1, 0, 1, 2, 0, 3]. Write a command that will return an array consisting of all the elements of array_a that are larger than zero. Hint: Use logical expression as the index of the array.

In [84]:
array_a = [-1, 0, 1, 2, 0, 3]
new_arr = [num for num in array_a if num > 0]
new_arr

[1, 2, 3]

### Problem 22
Create an array $y = \begin{pmatrix}3 && 5 && 3\\ 2 && 2 && 5\\ 3 && 8 && 9\end{pmatrix}$ and calculate its transpose.

In [89]:
y = np.array([[3, 5, 3], [2, 2, 5], [3, 8, 9]])
y_transpose = y.T
y_transpose

array([[3, 2, 3],
       [5, 2, 8],
       [3, 5, 9]])

### Problem 23
Create a $2\times 4$ zero array.

In [92]:
array_z = np.zeros((2, 4))
array_z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Problem 24
Change the second column in the above array to 1.

In [95]:
for i in range(2):
    array_z[i][1] = 1
array_z

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.]])

### Problem 25
Write a magic command to clear all the variables in the Jupyter notebook.

In [6]:
# %reset # Warning: This will remove all the variables from the notebook.