## Chapter 3 Exercises

### Problem 1
Recall that the hyperbolic sine, denoted by sinh, is $(\exp (x)−\exp (−x)) / 2$ . Write a function my_sinh(x) where the output y is the hyperbolic sine computed on x. Assume that x is a 1 by 1 float.


In [38]:
import numpy as np

def my_sinh(x):
    return np.sinh(x)

print(my_sinh(1))

1.1752011936438014


### Problem 2
Write a function my_checker_board(n) where the output m is an n × n array with the following form: $$m = \begin{matrix}1 && 0 && 1 && 0 && 1\\ 0 && 1 && 0 && 1 && 0\\ 1 && 0 && 1 && 0 && 1\\ 0 && 1 && 0 && 1 && 0\\ 1 && 0 && 1 && 0 && 1\\\end{matrix}$$
Note that the upper-left element should always be 1. Assume that n is a strictly positive integer.

In [39]:
def my_checker_board(n):
    m = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            if (i + j) % 2 == 0:
                m[i][j] = 1
    return m

my_checker_board(5)

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

### Problem 3
Write a function my_triangle(b,h) where the output is the area of a triangle with base, b, and height, h. Recall that the area of a triangle is one-half the base times the height. Assume that b and h are just 1 by 1 float numbers.

In [40]:
def my_triangle(b, h):
    return 0.5*b*h

### Problem 4
Write a function my_split_matrix(m), where m is an array, the output is a list [m1, m2] where m1 is the left half of m, and m2 is the right half of m. In the case where there is an odd number of columns, the middle column should go to m1. Assume that m has at least two columns.

In [41]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def my_split_matrix(m):
    if np.shape(m)[1] % 2 == 1:
        return m[:,:int((np.shape(m)[1]+1)/2)], m[:,int((np.shape(m)[1]+1)/2):]
    else:
        return m[:,:int((np.shape(m)[1])/2)], m[:,int((np.shape(m)[1])/2):]

m1, m2 = my_split_matrix(mat)
m1, m2

(array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]]))

### Problem 5
Write a function my_cylinder(r,h), where r and h are the radius and height of a cylinder, respectively, and the output is a list [s, v] where s and v are the surface area and volume of the same cylinder, respectively. Recall that the surface area of a cylinder is $2\pi r^2 + 2\pi rh$, and the volume is $\pi r^2h$. Assume that r and h are 1 by 1 floats.

In [42]:
def my_cylinder(r, h):
    return [2*np.pi*r*r + 2*np.pi*r*h, np.pi*r*r*h]

my_cylinder(1, 5)

[37.69911184307752, 15.707963267948966]

### Problem 6
Write a function my_n_odds(a), where a is a one-dimensional array of floats and the output is the number of odd numbers in a.

In [43]:
def my_n_odds(a):
    s = 0
    for num in a:
        if int(num) - num  == 0 and int(num) % 2 == 1:
            s += 1
    return s

my_n_odds(np.arange(100))

50

### Problem 7
Write a function my_twos(m,n) where the output is an m × n array of twos. Assume that m and n are strictly positive integers.

In [44]:
def my_twos(m, n):
    return 2 * np.ones((m, n))

my_twos(4, 5)

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

### Problem 8
Write a lambda function that takes in input x and y, and the output is the value of x-y.

In [45]:
difference = lambda x, y: x-y
difference(5, 2)

3

### Problem 9
Write a function add_string(s1, s2) where the output is the concatenation of the strings s1 and s2.

In [46]:
def add_string(s1, s2):
    return s1 + s2

s1 = add_string("Programming", " ")
s2 = add_string("is ", "fun!")
add_string(s1, s2)

'Programming is fun!'

### Problem 10
Generate the following errors:
- TypeError: fun() missing 1 required positional argument: "a"
-  IndentationError: expected an indented block

### Problem 11
Write a function greeting(name, age) where name is a string, age is a float, and the output is a string "Hi, my name is XXX and I am XXX years old." where XXX are the input name and age, respectively.

In [47]:
def greeting(name, age):
    return f"Hi, my name is {name} and I am {age} years old."

greeting("John", 26)

'Hi, my name is John and I am 26 years old.'

### Problem 12
Let r1 and r2 be the radius of circles with the same center and let r2 > r1. Write a function my_donut_area(r1, r2) where the output is the area outside of the circle with radius r1 and inside the circle with radius r2. Make sure that the function is vectorized. Assume that r1 and r2 are one-dimensional arrays of the same size.

In [48]:
def my_donut_area(r1, r2):
    return np.pi*(r2**2 - r1**2)

my_donut_area(np.arange(1, 4), np.arange(2, 7, 2))

array([ 9.42477796, 37.69911184, 84.82300165])

### Problem 13
Write a function my_within_tolerance(A, a, tol) where the output is an array or list of the indices in A such that |A − a| < tol. Assume that A is a one-dimensional float list or array, and that a and tol are 1 by 1 floats.

In [49]:
def my_within_tolerance(A, a, tol):
    return [b for b in A if np.absolute(b-a) < tol]

my_within_tolerance([0, 1, 2, 3], 1.5, 0.75)


[1, 2]

### Problem 14
Write a function bounding_array(A, top, bottom) where the output is equal to the array A wherever bottom < A < top, the output is equal to bottom wherever A <= bottom, and the output is equal to top wherever A >= top. Assume that A is a one-dimensional float array and that top and bottom are 1 by 1 floats.

In [50]:
def bounding_array(A, top, bottom):
    lst = []
    for i in A:
        if i <= bottom:
            lst.append(bottom)
        elif i >= top:
            lst.append(top)
        else:
            lst.append(float(i))
    return lst

bounding_array(np.arange(-5, 6, 1), 3, -3)

[-3, -3, -3, -2.0, -1.0, 0.0, 1.0, 2.0, 3, 3, 3]