## Chapter 4 Exercises

### Problem 1
Write a function my_tip_calc(bill, party) where bill is the total cost of a meal and party is the number of people in the group. The tip should be calculated as 15% for a party strictly less than six people, 18% for a party strictly less than eight, 20% for a party less than 11, and 25% for a party 11 or more.

In [3]:
def my_tip_calc(bill, party):
    if party < 6:
        tip = bill*15/100
    elif party < 8:
        tip = bill*18/100
    elif party < 11:
        tip = bill/5
    else:
        tip = bill/4
    return tip

print(my_tip_calc(109.29, 3))
print(my_tip_calc(109.29, 7))
print(my_tip_calc(109.29, 9))
print(my_tip_calc(109.29, 12))

16.393500000000003
19.6722
21.858
27.3225


### Problem 2
Write a function my_mult_operation(a,b,operation). The input argument, operation, is a string that is either "plus", "minus", "mult", "div", or "pow", and the function should compute: a + b, a − b, a ∗ b, a/b, and ab for the respective values for operation. A couple of test cases are given below.

In [4]:
import numpy as np

In [5]:
def my_mult_operation(a, b, operation):
    if operation == "plus":
        return a + b
    elif operation == "minus":
        return a- b
    elif operation == "multiply":
        return a*b
    elif operation == "divide":
        return a/b
    elif operation == "pow":
        return a**b

x = np.array([1,2,3,4])
y = np.array([2,3,4,5])

print(my_mult_operation(x,y,"plus"))
print(my_mult_operation(x,y,"minus"))
print(my_mult_operation(x,y,"multiply"))
print(my_mult_operation(x,y,"divide"))
print(my_mult_operation(x,y,"pow"))

[3 5 7 9]
[-1 -1 -1 -1]
[ 2  6 12 20]
[0.5        0.66666667 0.75       0.8       ]
[   1    8   81 1024]


### Problem 3
Consider a triangle with vertices at (0, 0), (1, 0), and (0, 1). Write a function with the name my_inside_triangle(x,y) where the output is the string "outside" if the point (x, y) is outside of the triangle, "border" if the point is exactly on the border of the triangle, and "inside" if the point is on the inside of the triangle.

In [6]:
p1 = (0, 0)
p2 = (1, 0)
p3 = (0, 1)

def my_inside_triangle(x, y):
    if x > 0 and y > 0 and x + y < 1:
        return "inside"
    elif x == 0 or y == 0 or x + y == 1:
        return "border"
    else:
        return "outside"
    
print(my_inside_triangle(.5,.5))
print(my_inside_triangle(.25,.25))
print(my_inside_triangle(5,5))


border
inside
outside


### Problem 4
Write a function my_make_size10(x) where x is an array, and output is the first 10 elements of x if x has more than 10 elements, and output is the array x padded with enough zeros to make it length 10 if x has less than 10 elements.

In [41]:
def my_make_size10(x):
    lst = list(x)
    if len(x) == 10:
        return list(x)
    elif len(x) < 10:
        for i in range(10-len(x)):
            lst.append(0)
        return lst
    else:
        return list(x)[:10]
    
my_make_size10(range(1, 5))

[1, 2, 3, 4, 0, 0, 0, 0, 0, 0]

### Problem 5
Can you write my_make_size10 without using if-statements (i.e., using only logical and array operations)?

### Problem 6
Write a function my_letter_grader(percent) where the grade is the string "A+" if percent is greater than 97, "A" if percent is greater than 93, "A-" if percent is greater than 90, "B+" if percent is greater than 87, "B" if percent is greater than 83, "B-" if percent is greater than 80, "C+" if percent is greater than 77, "C" if percent is greater than 73, "C-" if percent is greater than 70, "D+" if percent is greater than 67, "D" if percent is greater than 63, "D-" if percent is greater than 60, and "F" for any percent less than 60. Grades exactly on the division should be included in the higher grade category.

In [20]:
def my_letter_grader(percent):
    if percent > 97:
        return "A+"
    elif percent > 90:
        return "A"
    elif percent > 90:
        return "A-"
    elif percent > 90:
        return "B+"
    elif percent > 90:
        return "B"
    elif percent > 90:
        return "B-"
    elif percent > 90:
        return "C+"
    elif percent > 90:
        return "C"
    elif percent > 90:
        return "C-"
    elif percent > 90:
        return "D+"
    elif percent > 90:
        return "D"
    elif percent > 90:
        return "D-"
    else:
        return "F"
    
print(my_letter_grader(97))
print(my_letter_grader(84))

A
F



### Problem 7
Most engineering systems have a built-in redundancy. That is, an engineering system has fail-safes incorporated into the design to accomplish its purpose. Consider a nuclear reactor whose temperature is monitored by three sensors. An alarm should go off if any two of the sensor readings disagree. Write a function my_nuke_alarm(s1,s2,s3) where s1, s2, and s3 are the temperature readings for sensor 1, sensor 2, and sensor 3, respectively. The output should be the string "alarm!" if any two of the temperature readings disagree by strictly more than 10 degrees and "normal" otherwise.

In [24]:
def my_nuke_alarm(s1, s2, s3):
    if np.absolute(s1-s2) > 10 or np.absolute(s1-s3) > 10 or np.absolute(s2-s3) > 10:
        return "alarm!"
    else:
        return "normal"
    
print(my_nuke_alarm(94,96,90))
print(my_nuke_alarm(94,96,80))

normal
alarm!


### Problem 8
Let $Q(x)$ be the quadratic equation $Q(x) = ax^2 + bx + c$ for some scalar values $a, b$, and $c$. A root of $Q(x)$ is an $r$ such that $Q(r) = 0$. The two roots of a quadratic equation can be described by the quadratic formula, which is $r = \frac{-b\pm\sqrt{b^2-4ac}}{2a}.$ A quadratic equation has either two real roots (i.e., $b^2 > 4ac$), two imaginary roots (i.e., $b2 < 4ac$), or one root $r = − b/2a$. Write a function my_n_roots(a,b,c), where $a$, $b$, and $c$ are the coefficients of the quadratic $Q(x)$. The function should return two values: n_roots and r. Also n_roots is 2 if $Q$ has two real roots, 1 if $Q$ has one root, −2 if $Q$ has two imaginary roots, and r is an array containing the roots of $Q$.

In [11]:
import numpy as np
def my_n_roots(a, b, c):
    d = b**2 - 4*a*c
    if d > 0:
        return f"n_roots = {2}", f"r = {[(-b + np.sqrt(d))/(2*a), (-b - np.sqrt(d))/(2*a)]}"
    elif d == 0:
        return f"n_roots = {1}", f"r = {(-b + np.sqrt(d))/(2*a)}"
    else:
        return f"n_roots = {-2}", f"r = {[complex((-b)/(2*a), np.sqrt(-1*d)/(2*a)), complex((-b)/(2*a), -1*np.sqrt(-1*d)/(2*a))]}"
    
my_n_roots(3,4,5)

('n_roots = -2',
 'r = [(-0.6666666666666666+1.1055415967851332j), (-0.6666666666666666-1.1055415967851332j)]')

### Problem 9
Write a function my_split_function(f,g,a,b,x), where $f$ and $g$ are function objects $f(x)$ and $g(x)$, respectively. The output should be $f(x)$ if $x \leq a, g(x)$ if $x \geq b$, and 0 otherwise. Assume that $b > a$.

In [12]:
def my_split_function(f, g, a, b, x):
    if x <= a:
        return f(x)
    elif x>=b:
        return g(x)
    else:
        return 0
    
my_split_function(np.exp, np.sin, 2, 4, 1)

np.float64(2.718281828459045)